#!/usr/bin/env python

from lxml import etree, objectify
import argparse

# read and check the options
parser = argparse.ArgumentParser(description='Solr site indexing scaffold')
parser.add_argument('-d', '--document', dest='document', required=True, help='The document to process')
parser.add_argument('-t', '--transform', dest='transform', required=True, help='The XSLT transform')
args = parser.parse_args()

# read in the XSL transform 
xslt = etree.parse(args.transform)
#print etree.tostring(xslt, pretty_print=True)

# handle any includes
xslt.xinclude()

# read the document to be transformed
parser = etree.XMLParser(ns_clean=True, load_dtd=False, no_network=True)
doc = objectify.parse(args.document, parser)
#print etree.tostring(doc, pretty_print=True)

# transform it
#  we'll assume the transform will actually load
#  so we won't bother with exceptions
transform = etree.XSLT(xslt)
d = transform(doc)

# write to stdout
print etree.tostring(d, pretty_print=True, method="html")

